spring:
   profiles:
      active: dev
management:
   endpoints:
      web:
         exposure:
            include: info,health,beans,env,metrics,httptrace,features,release-notes,shutdown
   endpoint:
      shutdown:
         enabled: true
info:
   app:
      name: Product Catalog App
      description: Product Catalog application for inventory system