server:
   port: 8081
spring:
   datasource:
      url:
      username:  
      password:  
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         show-sql: true
features:
   order:
      enabled: false
   product:
      enabled: true